language: python
python:
    - "2.7"
env:
    - DJANGO=1.3.3
    - DJANGO=1.4.1
install:
    - pip install raven --use-mirrors
    - pip install Django==$DJANGO --use-mirrors
script:
    - python -m unittest test
